Repository lexmin0412/dify-chat, pull requests merged in 2025-05, with the labels that each got.

#254 Lexmin0412/issue248
  README.md
  docs/guide_app_config_opening_statement_display_always.png
  packages/components/src/chatbox/app-input-wrapper.tsx
  packages/components/src/chatbox/index.tsx
  packages/components/src/chatbox/welcome-placeholder.tsx
  packages/core/README.md
  packages/core/src/constants/app.ts
  packages/core/src/repository/app/index.ts
  src/components/app-edit-drawer.tsx
  src/components/app-manage-drawer.tsx
  src/components/setting-form.tsx
Labels: size:L

#255 支持消息重新生成
  packages/components/src/chatbox/index.tsx
  packages/components/src/chatbox/message/action-btn.tsx
  packages/components/src/chatbox/message/footer.tsx
Labels: size:M

#258 Lexmin0412/issue177
  packages/components/src/chatbox/message/referrence.tsx
  src/hooks/useX/index.ts
Labels: size:S

#259 optimize(ChatboxWrapper): 对话由临时 ID 变为真实 ID 时, 消息列表加载不再展示 loading, 提升用户体验
  src/components/chatbox-wrapper.tsx
Labels: size:S

#262 增加docker时区配置
  docker/.env
Labels: size:XS

#263 修复docker容器部分url刷新后报错404的问题
  docker/nginx/conf.d/default.conf.template
Labels: bug, size:S

#264 修复docker容器访问logo.png报错403的问题
  Dockerfile
Labels: bug, size:XS

#276 修复docker构建问题
  Dockerfile
Labels: size:XS
